import numpy as np
print('Splitting NumPy Arrays => array_split()')
arr = np.array([1,2,3,4,5,6,7,8,9])
result = np.array_split(arr, 4)
print(result[0])
print(result[1])
print(result[2])
print(result[3])

print('\nSplitting 2-D Array')
arr = np.array([[1,2],[3,4],[5,6],[7,9]])
result = np.array_split(arr, 2)
print(result)
print(result[0])
print(result[1])

print('\nSplitting 3-D Array')
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
result = np.array_split(arr, 1)
print(result)
print(result[0])

print('\nSplitting 2-D Array using hsplit')
arr = np.array([[1,2],[3,4],[5,6],[7,9]])
result = np.hsplit(arr, 2)
print(result)
print(result[0])
print(result[1])

print('\nSplitting 2-D Array using vsplit')
arr = np.array([[1,2],[3,4],[5,6],[7,9]])
result = np.vsplit(arr, 2)
print(result)
print(result[0])
print(result[1])

print('\nSplitting 3-D Array using dsplit')
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
result = np.hsplit(arr, 2)
print(result)
print(result[0])
print(result[1])
