import numpy as np
print('Numpy Summations => add')
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
result = np.add(arr1, arr2)
print(result)

print('\nNumpy Summations => sum')
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
result = np.sum([arr1, arr2])
print(result)

print('\nNumpy Summations => summation over an axis')
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.array([[1,2,3,4],[1,2,3,4]])
arr4 = np.array([[5,6,7,8],[5,6,7,8]])
result1 = np.sum([arr1, arr2], axis = 0)
result2 = np.sum([arr1, arr2], axis = 1)
result3 = np.sum([arr3, arr4], axis = 0)
result4 = np.sum([arr3, arr4], axis = 1)
result5 = np.sum([arr3, arr4], axis = 2)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)

print('\nNumpy Summations => Cummulative Sum')
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3,4,5,6])
result1 = np.cumsum(arr1)
result2 = np.cumsum(arr2)
print(result1)
print(result2)