import numpy as np
print('NumPy Products => prod()')
arr = np.array([1,2,3,4,5])
result = np.prod(arr)
print(result)

print('\nNumPy Products => product of 2 arrays')
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
result = np.prod([arr1, arr2])
print(result)

print('\nNumPy Products => product over an axis')
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
result1 = np.prod([arr1, arr2], axis = 0)
result2 = np.prod([arr1, arr2], axis = 1)
print(result1)
print(result2)

print('\nNumPy Products => Cummulative Product')
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
result1 = np.cumprod(arr1)
result2 = np.cumprod([arr1, arr2])
result3 = np.cumprod([arr1, arr2], axis = 0)
result4 = np.cumprod([arr1, arr2], axis = 1)
print(result1)
print(result2)
print(result3)
print(result4)