import numpy as np
print('Hyperbolic Functions')
x = np.sinh(np.pi/6) 
y = np.cosh(np.pi/6) 
z = np.tanh(np.pi/6)
print(x)
print(y)
print(z)

print('\nHyperbolic Functions => In Array')
arr = np.array([np.pi, np.pi/2, np.pi/3, np.pi/4, np.pi/5, np.pi/6])
result1 = np.sinh(arr)
result2 = np.cosh(arr)
result3 = np.tanh(arr)
print(result1)
print(result2)
print(result3)

print('\nFinding Angles')
x = np.arcsinh(1.0)
y = np.arccosh(2)
z = np.arctanh(0.5)
print(x)
print(y)
print(z)

print('\nAngles of Each Value in Arrays')
arr1 = np.array([0.1,2,.3,4])
arr2 = np.array([1.5,2,6,4])
arr3 = np.array([0.1,0.2,0.7])
result1 = np.arcsinh(arr1)
result2 = np.arccosh(arr2)
result3 = np.arctanh(arr3)
print(result1)
print(result2)
print(result3)